// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGnmoDuF_YY6J67x-2hdXcyKDbvqDXkpc',
    appId: '1:42645066870:web:c4b03bc2d79fdf05ae7b57',
    messagingSenderId: '42645066870',
    projectId: 'lung-disease-vgg16',
    authDomain: 'lung-disease-vgg16.firebaseapp.com',
    storageBucket: 'lung-disease-vgg16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwcbs6bmZgIuNRFo1yRJ_mckykeEfUJe0',
    appId: '1:42645066870:android:36b5818ce0432500ae7b57',
    messagingSenderId: '42645066870',
    projectId: 'lung-disease-vgg16',
    storageBucket: 'lung-disease-vgg16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHbodBgGod1jhwX8GVmwEyO7-69zy_a6s',
    appId: '1:42645066870:ios:82f4cf46e939a547ae7b57',
    messagingSenderId: '42645066870',
    projectId: 'lung-disease-vgg16',
    storageBucket: 'lung-disease-vgg16.appspot.com',
    iosClientId: '42645066870-t5dmon8eke9p6utedtjlfb8kpr5skdg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnn',
  );
}
